version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: reservation_postgres
    environment:
      POSTGRES_DB: reservation_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map host port to container port
    networks:
      - reservation_management

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_reservation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reservation.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - reservation_management
#  mysqldb:
#    container_name: mysqldb
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: passer123
#      MYSQL_PASSWORD: passer123
#      MYSQL_DATABASE: reservation_management
#    ports:
#      - "3306:3306"
#    networks:
#      reservation_management:

  reservation_management-api:
    container_name: reservation_management-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      reservation_management:
    restart: on-failure

volumes:
  postgres-data:

networks:
  reservation_management:
    driver: bridge
